repos:
  # -------------------------------
  # General hygiene
  # -------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict

  # -------------------------------
  # Terraform
  # -------------------------------
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_docs

  # -------------------------------
  # Kubernetes YAML
  # -------------------------------
  - repo: https://github.com/yannh/kubeconform
    rev: v0.6.7
    hooks:
      - id: kubeconform
        args:
          - "-strict"
          - "-ignore-missing-schemas"

  # -------------------------------
  # Security scanning (Terraform + YAML)
  # -------------------------------
  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.524
    hooks:
      - id: checkov

  # -------------------------------
  # Python (your app/)
  # -------------------------------
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8